### ISSUE TITLE
Dashboard compatibility

### ISSUE THREAD

**Issue by AT0myks** [iwalton3/media-scripts#1]
I don't know how to add an enhancement label and I'm not sure if opening a pull request is appropriate as I've just modified one file, but anyway, for Plex Web, if you replace `url.indexOf("/library/metadata/") == -1` by `url.indexOf("/library/metadata/") == -1 && url.indexOf("/status/sessions") == -1` the changes also apply to the dashboard.
One issue is it doesn't work when transcoding is involved but I haven't looked into it yet.
![plex](https://user-images.githubusercontent.com/49416996/81769230-5e5c1e00-94dd-11ea-9e58-8b5ef7d32300.jpg)
And by the way, huge thanks for this, this is a feature I've been wanting since I started using Plex.

**Comment by iwalton3** [comment]
This has been implemented for Direct Play as described. I looked at the API communications for transcoded files, and the structure is different enough that the data simply isn't there to modify.
