### ISSUE TITLE
Does this script change the "Signs" subs "flag" inside the files?

### ISSUE THREAD

**Issue by Dokixi** [iwalton3/media-scripts#3]
Hi,

I have just one question. Does your script run through every file and find every english "Signs & Songs" track, then changes the flag from "no" to "forced"? 🤔 I hope it dosen’t mess with any of my "default" flags tho. I'm primarely a anime sub watcher, so I have every file, either dual audio or not, set with "japanese audio" as "default", and "Full english" subtitles as "default".

Also, how do you change the script to make it look for more variations of "Signs" subs with a bit different track name? 🤔

**Comment by iwalton3** [comment]
Yes the force-signs script sets the forced attribute on sign/karaoke subtitles (if it can detect them) and leaves the default alone.

**Comment by Dokixi** [comment]
Awesome 👍🏻

Btw, just for clarification.

Is it correct to have a setup like this for anime sub viewing:
"Japanese audio (Default flag)" and
(English Full Subtitles -> Default flag)"

But then having the "Signs & Songs" set to be "forced"? Where the "forced" tag is supposed to kick in when switching to the English audio track? (Depends on the player ofcourse)

Is this the correct logic behind "forced"?

**Comment by iwalton3** [comment]
The script was built for Plex, which defaults to forced and English audio. Then I have a separate script that tells Plex not to play forced audio/subtitles if desired.

The approach is a little outdated though, as MPV Shim (for both Plex and Jellyfin) auto detects based on title and doesn’t need the forced tag. Jellyfin Media Player uses a different implementation entirely, opting to attempt to select the same tracks as the previous video.

**Comment by Dokixi** [comment]
Aha, okay.

Well, then I'm probably not going to go ahead with the forced-subs-script, unless I would need to in the future for some reason.

Sounds like MPV Shim is just easier to use instead of opting the "forced" tag logic. And for my needs, I can get by with not using the "Forced" tag at all for my anime anyway. All of my subtitle tracks are properly name too.

But thanks for your help tho. Really appriciate it. And you've done a great job with all of these scripts and making a Plex client for handling subtitles the proper way.
